### ISSUE TITLE
Choose câmera in mobile

### ISSUE THREAD

**Issue by Marcdnd** [decred/copay#1]
There is no way to choose the camera on the mobile phone.

Android 5 - Chrome

**Comment by jcvernaleo** [comment]
So this doesn't really work properly in any mobile browser I tested.  Totally different problems for each browser of course.  I believe it is really only meant for the mobile app (which we aren't working on yet) so I've disabled the feature all together.  If we ever do the mobile app we can re-enable it there.

Thanks for reporting!
