### ISSUE TITLE
Initial redirect goes to the wrong place

### ISSUE THREAD

**Issue by davecgh** [decred/copay#10]
When you go to https://wallet.decred.org with no wallet, as is the case for all new users, it currently automatically redirects to https://wallet.decred.org/#/import.

Instead, this should redirect to https://wallet.decred.org/#/add or even https://wallet.decred.org/#/create because a new user will not have created their wallet yet.

This has caused a lot of confusion for many users because it starts them on the import screen where they enter their seed and get an error that the wallet has not been registered yet.  The error message is accurate of course because the wallet has in fact not been created yet, but I think a lot of the confusion could be avoided if the initial landing page is changed to creating a wallet.

**Comment by jcvernaleo** [comment]
Not sure I understand (or possibly the behavior has changed).
With a fresh firefox profile, I go to https://wallet.decred.org
That redirects me to https://wallet.decred.org#disclaimer
From there I hit "Agree" and get sent to:
https://wallet.decred.org/#/splash
From there I have to choose either 'Get Started" (the larger option) or "Import Backup".
"Get Started" makes a new testnet wallet for me (one could argue if testnet is the right behavior or not but that's sort of a separate issue) and "Import Backup" goes to the import page.

So I'm not sure where the behavior you see is (or if I'm misunderstanding something).

**Comment by davecgh** [comment]
The issue is from the perspective of a new wallet user that already has a seed created by btcwallet (or any other means outside of the wallet.decred.org).

I have a seed I want to use, but when I go to https://wallet.decred.org, hit agree on the https://wallet.decred.org#disclaimer, there is no option to import the seed for a wallet that copay doesn't know about already.  Instead, after clicking "Import", you have to click the relatively hidden "Back" in the upper left corner and create a new wallet, etc.

See the guide I put up on the forums [here](https://forum.decred.org/threads/guide-with-screenshots-to-claim-airdrop-coins-with-wallet-decred-org.643/) to make it more clear what I'm talking about.

**Comment by peterzen** [comment]
Copay 3.x redirects to the onboarding flow which should fix this issue.
