### ISSUE TITLE
Proposal: uri handler for decred: on the webwallet. 

### ISSUE THREAD

**Issue by Borkmywork** [decred/copay#14]
It would be nice if there was an uri handler for copay. 

this to ease up the payments for everybody. 

[decred:DsUFoP9Hvs769GSdmL8U6TpDYQyyqyL4kBS](url)

The example above would link you to the webwallet with the address already filled in.

**Comment by timhoekstra** [comment]
If could be possible but Internet Explorer and Safari would be left out. See http://caniuse.com/#feat=registerprotocolhandler
Does anybody have an idea for those browsers?

**Comment by jcvernaleo** [comment]
We already have:
navigator.registerProtocolHandler('web+decred', url, 'DecredWebWallet');

In firefox when I first go to copay it asks me if I want to register wallet as a handler for those links.  I believe it is supposed to work in chrome too.  So I'm not totally sure what you want that isn't covered by that.  Is it not working in a particular browser?

**Comment by jcvernaleo** [comment]
Since it has been over a month without hearing back I'm going to close this issue since there really isn't any action I can take.  I think we already do what you wanted (by registering the ProtocolHandler).  If I'm wrong, please feel free to reopen the issue.
