### ISSUE TITLE
Can't see balance amount.

### ISSUE THREAD

**Issue by Retord** [decred/copay#15]
In https://mainnet.decred.org/address/ 
I can clearly see the amount of coins I have.
But when I import the seed to wallet.decred.org.
I see nothing.
http://i.imgur.com/EW3LilA.png

I even did a scan of addresses. Still it shows nothing.

http://i.imgur.com/vUU6SYo.png

**Comment by alexlyp** [comment]
this was due to cached js that needed to be flushed to pick up new client side js.
Fixed now.
