### ISSUE TITLE
View transaction in transaction history leads to testnet transactions on mainnet

### ISSUE THREAD

**Issue by cjepson** [decred/copay#2]
When attempting to look up your transaction ID in mainnet transaction history, you are given a URL to the testnet explorer.

**Comment by jcvernaleo** [comment]
This one I'll get to tomorrow.

**Comment by jcvernaleo** [comment]
This is fixed in commit 66ae5425a7b7af1ca2da7710cbebae35cd75e4af

**Comment by jcvernaleo** [comment]
This should be correct on the site now.
