### ISSUE TITLE
Mainnet wallets in copay come up as testnet wallets on the front page

### ISSUE THREAD

**Issue by cjepson** [decred/copay#3]
The text on the left hand size of a mainnet wallet still says "Testnet", even though the addresses and transactions generated are on mainnet.

**Comment by jcvernaleo** [comment]
This was fixed in 364f2e3aa21

The live version must not have been updated.

**Comment by jcvernaleo** [comment]
I'll leave this open until it gets updated

**Comment by jcvernaleo** [comment]
This is now correct on the live site.
