### ISSUE TITLE
Validate 0.4.0 release

### ISSUE THREAD

**Issue by marcopeereboom** [decred/copay#35]
Vlidate decred-copay on the following arches:
- [x] OSX
- [x] Windows 7
- [x] Windows 10
- [x] Linux

Duplicate test welcome and do check off what has been tested.

In the comments note what you tested and the results.

**Comment by jcvernaleo** [comment]
OSX seems to work.  I didn't test exhaustively, but it runs and looks fine.

**Comment by jcvernaleo** [comment]
Win7 fails immediately with a generic 'PROGRAM has stopped working' error from windows.

**Comment by jcvernaleo** [comment]
The linux one works on Ubuntu 16.04 amd64 at least.  Other linuxes should probably give it a shot too.

**Comment by alexlyp** [comment]
linux version works great on Fedora 21.   Sent/Received funds on testnet wallet and 2of3 testnet as well.

**Comment by jcvernaleo** [comment]
For future reference, on win7, in a console the result it:
```
$ ./decred-copay-windows-v0.4.0.exe
[2772:0901/172151:ERROR:icu_util.cc(152)] Couldn't mmap C:\Users\jcv\Desktop\icudtl.dat
[2772:0901/172151:FATAL:content_main_runner.cc(749)] Check failed: base::i18n::InitializeICU().
```

**Comment by jolan** [comment]
Tested linux on Arch, did various tests and it behaves like the web wallet as expected.

Windows version on Win10 silently exits.  No output at all.

**Comment by marcopeereboom** [comment]
Decision has been made not to ship windows this release.

**Comment by marcopeereboom** [comment]
Looks like we found the culprit so let's redo windows.

**Comment by jcvernaleo** [comment]
With the new builds win7 seems to work for me.

**Comment by jolan** [comment]
New build works on Win10 64-bit too.

**Comment by marcopeereboom** [comment]
So this works on windows 10 but it is pretty ugly.  I am not ok shipping this as is so we are not going to ship it until the next release.

We need proper installs for windows instead of this hodgepodge.
