### ISSUE TITLE
Mainnet fees are calculated incorrectly

### ISSUE THREAD

**Issue by cjepson** [decred/copay#4]
To be included in the blockchain, a minimum of 0.05 Coins/KB is required. The current software does not specify the correct amount of fees required and can result in a user's funds being stuck in limbo.

**Comment by jcvernaleo** [comment]
This has been patched in the live wallet.  Fix will be committed tomorrow.

**Comment by jcvernaleo** [comment]
This was fixed in 2aaab2c8eb933553fe57c66cdfea4636cb45cf76

**Comment by jcvernaleo** [comment]
That commit is from decred/bitcore-wallet-service and apparently I don't know how to link to commits in other repos.
