### ISSUE TITLE
Insufficient funds for fee when using the "send all" button 

### ISSUE THREAD

**Issue by rickpalmeira** [decred/copay#7]
The web wallet returns the following error to me when I use the "send all" button. isn't it already discounting it?

![screenshot from 2016-02-11 17-02-44](https://cloud.githubusercontent.com/assets/4140033/12987310/a0fd990a-d0e2-11e5-80b6-047e5e5433d0.png)

**Comment by alexlyp** [comment]
Thanks for the issue, and apologies for the delay in response.

I have submitted a PR that appears to fix this issue
